### ISSUE TITLE
Logger-style provider definition

### ISSUE THREAD

**Issue by FilipMalczak** [helsing/valid4j#5]
I feel that contracts serve quite a similar role as loggers - they are bug tracking tools at their core (lets not get into log parsing right now, ok?). In the spirit of logger configs (e.g. [1](https://logging.apache.org/log4j/2.x/manual/configuration.html), [2](https://logging.apache.org/log4j/2.x/manual/configuration.html)) how about we let user configure policies package-/class-wide?

I'd imagine that,

given a config file like:

```yaml
providers:
  all-policies:
    require: check
    ensure: check
    neverGetHere: check

configure: #very debatable
  _: all-policies # means "by default";also debatable
  org.example:
    require: pass
  org.depdendency:
    require: pass
    ensure: pass
  org.example.newfeature.AType:
    neverGetHere: pass #stupid idea for examples sake
```

we'd need a policy like:

```java
class ConfigurableProvider implements AssertiveProvider {
  final static CheckPolicy check = new CheckingPolicy();
  final static CheckPolicy pass = new NonCheckingPolicy();
  final static UnreachablePolicy ignore = new DoNothingPolicy();
  final static UnreachablePolicy goNuts = new NeverGetHerePolicy();

  Config config;

  CheckPolicy requirePolicy(){
    if (config.for(getCallerClass() == ConfigValue.CHECK) {
      return check;
    } else {
      return pass;
    }
  }

  (...) //you can guess for ensure
  
  UnreachablePolicy neverGetHerePolicy(){
    if (config.for(getCallerClass() == ConfigValue.CHECK) {
      return goNuts;
    } else {
      return ignore;
    }
  }
}
```

This was written ad-hoc, so it terribly simplified. I'd be happy to start working on PR, but first I wanted to discuss if that's the direction you wanna go with.
